In [1]:
from __future__ import print_function
from osgeo import gdal

print("GDAL's version is: " + gdal.__version__)
print(gdal)

GDAL's version is: 3.6.4
<module 'osgeo.gdal' from '/usr/local/lib/python3.10/dist-packages/osgeo/gdal.py'>


In [12]:
dataset = gdal.Open('LC08_L2SP_116034_20240728_20240801_02_T1_ST_B10.TIF', gdal.GA_ReadOnly)

print(dataset)



<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7c0d326f6bb0> >


In [15]:
num_bands = dataset.RasterCount
print('Number of bands in image: {n}\n'.format(n=num_bands))

rows = dataset.RasterYSize
cols = dataset.RasterXSize
print('Image size is: {r} rows x {c} columns\n'.format(r=rows, c=cols))

desc = dataset.GetDescription()
metadata = dataset.GetMetadata()

print('Raster description: {desc}'.format(desc=desc))
print('Raster metadata:')
print(metadata)
print('\n')

driver = dataset.GetDriver()
print('Raster driver: {d}\n'.format(d=driver.ShortName))

blue = dataset.GetRasterBand(1)
print(blue)

Number of bands in image: 1

Image size is: 7971 rows x 7841 columns

Raster description: LC08_L2SP_116034_20240728_20240801_02_T1_ST_B10.TIF
Raster metadata:
{'AREA_OR_POINT': 'Point'}


Raster driver: GTiff

<osgeo.gdal.Band; proxy of <Swig Object of type 'GDALRasterBandShadow *' at 0x7c0ceb4d93b0> >


In [19]:
datatype = blue.DataType
print('Band datatype: {dt}'.format(dt=blue.DataType))

datatype_name = gdal.GetDataTypeName(blue.DataType)
print('Band datatype: {dt}'.format(dt=datatype_name))

bytes = gdal.GetDataTypeSize(blue.DataType)
print('Band datatype size: {b} bytes\n'.format(b=bytes))

band_max, band_min, band_mean, band_stddev = blue.GetStatistics(0,1)
print('Band range: {minimum} - {maximum}'.format(maximum=band_max,
                                                 minimum=band_min))
print('Band mean, stddev: {m}, {s}\n'.format(m=band_mean, s=band_stddev))

blue_data = blue.ReadAsArray()

Band datatype: 2
Band datatype: UInt16
Band datatype size: 16 bytes

Band range: 49685.0 - 293.0
Band mean, stddev: 14862.5547395, 14883.051441326



In [20]:
import numpy
print(numpy.__version__)

import numpy as np
print(np.__version__)

image = np.zeros((dataset.RasterYSize, dataset.RasterXSize, dataset.RasterCount))

for b in range(dataset.RasterCount):
    band = dataset.GetRasterBand(b + 1)

    image[:, :, b] = band.ReadAsArray()

print(image)
print(image.dtype)

1.26.4
1.26.4
[[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]]
float64
